### ISSUE TITLE
`apm airsdk *` fails

### ISSUE THREAD

**Issue by j3k0** [airsdk/apm#73]
The `airsdk` commands fail. The root of the issue is in Harman's `/releases` API [1].

A note about, I guess it would be nice if the `apm-repository` had an API endpoint that proxies those requests to Harman:

 1. If the API URL changes, it can be fixed for everyone by changing the apm server configuration (no need to deploy a new version of the client).
 2. If the format of the response changes, it could be fixed server-side too.
 3. It could also do some caching and contain an hard coded fallback response:
    * so that in case the upstream API is unreachable (like it is now) or provides an incorrect response, `apm airsdk` would still work.

---

[1]

```
$ curl https://dcdu3ujoji.execute-api.us-east-1.amazonaws.com/production/releases | jq .
```

```json
{
  "errorType": "TypeError",
  "errorMessage": "Cannot read property 'origin' of undefined",
  "trace": [
    "TypeError: Cannot read property 'origin' of undefined",
    "    at Runtime.exports.handler (/var/task/index.js:220:31)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

**Comment by marchbold** [comment]
I suppose you are assuming that the air sdk repository is more stable than the aws endpoint :) 

Not sure what has happened there, will reach out to harman as this affects the airsdk.dev site as well.

**Comment by marchbold** [comment]
@ajwfrost Any idea as to what's happened to the `/releases` endpoint. The others seem to be working eg 

https://dcdu3ujoji.execute-api.us-east-1.amazonaws.com/production/releases/latest

**Comment by marchbold** [comment]
@j3k0 Just to elaborate further, this API pretty much was made available for apm so changes to it would most likely be at the request of apm (or related tools that we develop). So handling changes at the server again isn't a scenario I think we need to account for.
